# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/course22p2',
                'doc_host': 'https://fastai.github.io',
                'git_url': 'https://github.com/fastai/course22p2',
                'lib_path': 'miniai'},
  'syms': { 'miniai.training': { 'miniai.training.Dataset': ('minibatch.html#dataset', 'miniai/training.py'),
                                 'miniai.training.Dataset.__getitem__': ('minibatch.html#__getitem__', 'miniai/training.py'),
                                 'miniai.training.Dataset.__init__': ('minibatch.html#__init__', 'miniai/training.py'),
                                 'miniai.training.Dataset.__len__': ('minibatch.html#__len__', 'miniai/training.py'),
                                 'miniai.training.accuracy': ('minibatch.html#accuracy', 'miniai/training.py'),
                                 'miniai.training.fit': ('minibatch.html#fit', 'miniai/training.py'),
                                 'miniai.training.get_dls': ('minibatch.html#get_dls', 'miniai/training.py'),
                                 'miniai.training.report': ('minibatch.html#report', 'miniai/training.py')}}}