# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/001_fast_progress_fix.ipynb.

# %% auto 0
__all__ = ['update_patch']

# %% ../notebooks/001_fast_progress_fix.ipynb 2
from IPython.display import clear_output, DisplayHandle
def update_patch(self, obj):
    clear_output(wait=True)
    self.display(obj)
DisplayHandle.update = update_patch
